name: Merger CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run a multi-line script
      run: |
        mkdir -p dist
        cat src/*.js > dist/hugo_shortcodes_netlify_cms.js
    - name: Add & Commit files
      run: |
        git config --local user.email "dev_sharad@outlook.com"
        git config --local user.name "sharadcodes"
        git add .
        git commit -m "Added Changes & Merged File" -a
        git push -f -q https://${{ secrets.GITHUB_TOKEN }}@github.com/sharadcodes/hugo-shortcodes-netlify-cms.git master
